import { HeaderWrapper, FooterWrapper } from '../components/LayoutWrappers'

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[#0a0a0f] text-white">
      <HeaderWrapper />

      <main className="flex-1 pt-16">
        <section className="py-20 px-6">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl md:text-5xl font-black mb-6">Terms of Service</h1>
            <p className="text-gray-400 mb-12">Last updated: December 2024</p>

            <div className="prose prose-invert prose-orange max-w-none">
              <h2>Acceptance of Terms</h2>
              <p>By using GTM Quest, you agree to these terms of service.</p>

              <h2>Use of Service</h2>
              <p>Our service provides go-to-market strategy tools, provider directories, and market intelligence for informational and planning purposes.</p>

              <h2>AI-Generated Content</h2>
              <p>GTM plans and recommendations generated by our AI are provided as guidance and should be reviewed and adapted to your specific business needs. We do not guarantee specific business outcomes.</p>

              <h2>User Content</h2>
              <p>You retain ownership of information you provide to generate GTM plans. By using our service, you grant us permission to process this information for strategy generation.</p>

              <h2>Provider Directory</h2>
              <p>Information about GTM providers is compiled for informational purposes. We do not endorse any specific provider and recommend conducting your own due diligence.</p>

              <h2>Intellectual Property</h2>
              <p>All content, features, and functionality of GTM Quest are owned by us and protected by intellectual property laws.</p>

              <h2>Limitation of Liability</h2>
              <p>GTM Quest is provided "as is" without warranties. We are not liable for any damages arising from your use of the service or reliance on AI-generated recommendations.</p>

              <h2>Contact</h2>
              <p>For questions, contact us at legal@gtm.quest.</p>
            </div>
          </div>
        </section>
      </main>

      <FooterWrapper />
    </div>
  )
}
